# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_delete_usermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1111-11-11'),
        ),
    ]
